import { PERMISSIONS } from './permissions.js';

export const ROLES = {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    SALES: 'SALES_STAFF',
    OPERATIONS: 'OPERATIONS_STAFF',
    CUSTOMER: 'CUSTOMER',
};

export const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: [
        PERMISSIONS.MANAGE_ROLES,
        PERMISSIONS.MANAGE_PERMISSIONS,
        PERMISSIONS.MANAGE_SYSTEM_CONFIG,
        PERMISSIONS.MANAGE_ALL_USERS,
        PERMISSIONS.VIEW_SYSTEM_LOGS,
    ],
    [ROLES.MANAGER]: [
        PERMISSIONS.MANAGE_PRODUCTS,
        PERMISSIONS.MANAGE_PRICING,
        PERMISSIONS.MANAGE_PROMOTIONS,
        PERMISSIONS.MANAGE_USERS,
        PERMISSIONS.VIEW_REPORTS,
        PERMISSIONS.MANAGE_POLICIES,
    ],
    [ROLES.SALES]: [
        PERMISSIONS.VIEW_ORDERS,
        PERMISSIONS.VALIDATE_PRESCRIPTION,
        PERMISSIONS.CONTACT_CUSTOMER,
        PERMISSIONS.CONFIRM_ORDER,
        PERMISSIONS.HANDLE_PREORDER,
        PERMISSIONS.HANDLE_RETURNS,
    ],
    [ROLES.OPERATIONS]: [
        PERMISSIONS.PACK_ORDER,
        PERMISSIONS.CREATE_SHIPMENT,
        PERMISSIONS.UPDATE_TRACKING,
        PERMISSIONS.PROCESS_PREORDER_INVENTORY,
        PERMISSIONS.PROCESS_PRESCRIPTION_ORDERS,
        PERMISSIONS.UPDATE_ORDER_STATUS,
    ],
    [ROLES.CUSTOMER]: [
        PERMISSIONS.VIEW_PRODUCTS,
        PERMISSIONS.SEARCH_PRODUCTS,
        PERMISSIONS.VIEW_PRODUCT_DETAIL,
        PERMISSIONS.MANAGE_CART,
        PERMISSIONS.CREATE_ORDER,
        PERMISSIONS.VIEW_OWN_ORDERS,
        PERMISSIONS.REQUEST_RETURN,
    ],
};
