CREATE DATABASE IF NOT EXISTS eyewear_system
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE eyewear_system;

CREATE TABLE IF NOT EXISTS role (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	description VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `user` (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	role_id BIGINT UNSIGNED NOT NULL,
	full_name VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	phone VARCHAR(30) NULL,
	status ENUM('active', 'inactive', 'blocked') DEFAULT 'active',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES role(id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS product (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	slug VARCHAR(180) NOT NULL UNIQUE,
	description TEXT NULL,
	base_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
	brand VARCHAR(80) NULL,
	gender ENUM('unisex', 'men', 'women', 'kids') DEFAULT 'unisex',
	is_active TINYINT(1) NOT NULL DEFAULT 1,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS productvariant (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	product_id BIGINT UNSIGNED NOT NULL,
	sku VARCHAR(100) NOT NULL UNIQUE,
	color VARCHAR(60) NULL,
	size VARCHAR(60) NULL,
	price_override DECIMAL(12,2) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_productvariant_product FOREIGN KEY (product_id) REFERENCES product(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS inventory (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	productvariant_id BIGINT UNSIGNED NOT NULL UNIQUE,
	quantity INT UNSIGNED NOT NULL DEFAULT 0,
	reserved_quantity INT UNSIGNED NOT NULL DEFAULT 0,
	reorder_level INT UNSIGNED NOT NULL DEFAULT 5,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_inventory_productvariant FOREIGN KEY (productvariant_id) REFERENCES productvariant(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lens (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	lens_type VARCHAR(80) NOT NULL,
	index_value DECIMAL(4,2) NULL,
	coating VARCHAR(120) NULL,
	price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS promotion (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	code VARCHAR(60) NOT NULL UNIQUE,
	title VARCHAR(150) NOT NULL,
	discount_type ENUM('percentage', 'fixed') NOT NULL,
	discount_value DECIMAL(12,2) NOT NULL,
	starts_at DATETIME NOT NULL,
	ends_at DATETIME NOT NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 1,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	sph_od DECIMAL(5,2) NULL,
	sph_os DECIMAL(5,2) NULL,
	cyl_od DECIMAL(5,2) NULL,
	cyl_os DECIMAL(5,2) NULL,
	axis_od SMALLINT UNSIGNED NULL,
	axis_os SMALLINT UNSIGNED NULL,
	pd DECIMAL(5,2) NULL,
	notes TEXT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_prescription_user FOREIGN KEY (user_id) REFERENCES `user`(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cart (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	status ENUM('active', 'checked_out', 'abandoned') DEFAULT 'active',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES `user`(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cartitem (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cart_id BIGINT UNSIGNED NOT NULL,
	productvariant_id BIGINT UNSIGNED NOT NULL,
	lens_id BIGINT UNSIGNED NULL,
	prescription_id BIGINT UNSIGNED NULL,
	quantity INT UNSIGNED NOT NULL DEFAULT 1,
	unit_price DECIMAL(12,2) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_cartitem_cart FOREIGN KEY (cart_id) REFERENCES cart(id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_cartitem_productvariant FOREIGN KEY (productvariant_id) REFERENCES productvariant(id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_cartitem_lens FOREIGN KEY (lens_id) REFERENCES lens(id)
		ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT fk_cartitem_prescription FOREIGN KEY (prescription_id) REFERENCES prescription(id)
		ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `order` (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	promotion_id BIGINT UNSIGNED NULL,
	order_number VARCHAR(50) NOT NULL UNIQUE,
	total_amount DECIMAL(12,2) NOT NULL,
	discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
	shipping_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
	status ENUM('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded') DEFAULT 'pending',
	shipping_address TEXT NOT NULL,
	billing_address TEXT NULL,
	placed_at DATETIME NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES `user`(id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_order_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id)
		ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS orderitem (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_id BIGINT UNSIGNED NOT NULL,
	productvariant_id BIGINT UNSIGNED NOT NULL,
	lens_id BIGINT UNSIGNED NULL,
	prescription_id BIGINT UNSIGNED NULL,
	quantity INT UNSIGNED NOT NULL,
	unit_price DECIMAL(12,2) NOT NULL,
	line_total DECIMAL(12,2) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES `order`(id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_orderitem_productvariant FOREIGN KEY (productvariant_id) REFERENCES productvariant(id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_orderitem_lens FOREIGN KEY (lens_id) REFERENCES lens(id)
		ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT fk_orderitem_prescription FOREIGN KEY (prescription_id) REFERENCES prescription(id)
		ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS payment (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_id BIGINT UNSIGNED NOT NULL,
	payment_method ENUM('cod', 'bank_transfer', 'card', 'e_wallet') NOT NULL,
	amount DECIMAL(12,2) NOT NULL,
	status ENUM('pending', 'paid', 'failed', 'refunded') DEFAULT 'pending',
	transaction_ref VARCHAR(120) NULL,
	paid_at DATETIME NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES `order`(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shipment (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_id BIGINT UNSIGNED NOT NULL,
	courier VARCHAR(80) NULL,
	tracking_number VARCHAR(120) NULL UNIQUE,
	shipping_status ENUM('pending', 'packed', 'shipping', 'delivered', 'returned') DEFAULT 'pending',
	shipped_at DATETIME NULL,
	delivered_at DATETIME NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_shipment_order FOREIGN KEY (order_id) REFERENCES `order`(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS supportticket (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	order_id BIGINT UNSIGNED NULL,
	subject VARCHAR(180) NOT NULL,
	message TEXT NOT NULL,
	status ENUM('open', 'in_progress', 'resolved', 'closed') DEFAULT 'open',
	priority ENUM('low', 'medium', 'high', 'urgent') DEFAULT 'medium',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_supportticket_user FOREIGN KEY (user_id) REFERENCES `user`(id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_supportticket_order FOREIGN KEY (order_id) REFERENCES `order`(id)
		ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS returnrequest (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	orderitem_id BIGINT UNSIGNED NOT NULL,
	reason TEXT NOT NULL,
	status ENUM('pending', 'approved', 'rejected', 'completed') DEFAULT 'pending',
	requested_at DATETIME NOT NULL,
	resolved_at DATETIME NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_returnrequest_user FOREIGN KEY (user_id) REFERENCES `user`(id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_returnrequest_orderitem FOREIGN KEY (orderitem_id) REFERENCES orderitem(id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);
